'use client';
import { ReduxProviders } from '@/lib/redux/ReduxProvider';
import type { Metadata } from 'next';
import TanStackProviders from '@/lib/react-query/QueryProvider';
import MuiProvier from '@/lib/mui/MuiProvier';
// import RootStyleRegistry from '@/lib/styled-components/RootStyleRegistry';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko-kr">
      <body suppressHydrationWarning={true}>
        <ReduxProviders>
          <TanStackProviders>
            <MuiProvier options={{ key: 'mui' }}>
              <Container maxWidth="xl">
                <Box
                  sx={{
                    marginTop: 10,
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                  }}
                >
                  <div>
                    <Link href="/">메인 페이지로 이동</Link>
                  </div>
                  {children}
                </Box>
              </Container>
            </MuiProvier>
          </TanStackProviders>
        </ReduxProviders>
      </body>
    </html>
  );
}
