version: "3.3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3050:80"
    depends_on:
      - backend
      - frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/src/config/.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
